### ISSUE TITLE
Semester Scheduling Algorithm

### ISSUE THREAD

**Issue by L-Guidos** [kbef/group1apk#11]
Semester scheduling algorithm does not always produce correct/intended results

**Comment by L-Guidos** [comment]
@Ahmed-Har we need to add a statement to not allow someone to graduate on a coop term as per university requirements

**Comment by Ahmed-Har** [comment]
> @Ahmed-Har we need to add a statement to not allow someone to graduate on a coop term as per university requirements

I have fixed this issue. COOP 2180 should always be scheduled in the winter semester following COOP 2080. 
I have pushed the update to the Algorithm branch.

**Comment by L-Guidos** [comment]
This issue was dealt with in the latest pull request.
