### ISSUE TITLE
Database Upload from External File

### ISSUE THREAD

**Issue by L-Guidos** [kbef/group1apk#13]
Have database uploadable and downloadable from app

**Comment by L-Guidos** [comment]
I am working on this by adding an "Admin" button to the main activity. Goal is to have it password/verification code protected so that not all users can pull it. 

Need to look into reading/writing/proofing format of files

**Comment by L-Guidos** [comment]
Was able to override the back button. I set up a toast to notify the user that they need to use the logout. Should be able to override onBackPressed in other app areas

`@Override
    public void onBackPressed() {
        Toast.makeText(getApplicationContext(), "Use Logout button", Toast.LENGTH_SHORT).show();
    }`

**Comment by L-Guidos** [comment]
I have completed the database download. Have not yet started the database upload- if we do an upload, it would require @Ahmed-Har 's algorithm to run again from scratch and the user would lose their schedule because of the course changes. Thoughts, @Ahmed-Har , @kbef ?

**Comment by Ahmed-Har** [comment]
> I have completed the database download. Have not yet started the database upload- if we do an upload, it would require @Ahmed-Har 's algorithm to run again from scratch and the user would lose their schedule because of the course changes. Thoughts, @Ahmed-Har , @kbef ?

Does it not save the user's schedule in the backup table? If not, could that be a possible solution?

**Comment by L-Guidos** [comment]
I would also like to have the password extracted and set. I do not think the user would need to change this as it is admin and I would like to have it hidden in text view

**Comment by L-Guidos** [comment]
> > I have completed the database download. Have not yet started the database upload- if we do an upload, it would require @Ahmed-Har 's algorithm to run again from scratch and the user would lose their schedule because of the course changes. Thoughts, @Ahmed-Har , @kbef ?
> 
> Does it not save the user's schedule in the backup table? If not, could that be a possible solution?

@Ahmed-Har but the courses would change
