### ISSUE TITLE
Custom Schedule

### ISSUE THREAD

**Issue by L-Guidos** [kbef/group1apk#20]
Need to get custom scheduling algorithm created and implemented. @kbef is working on the integration with the app. @Ahmed-Har is working on the algorithm

**Comment by kbef** [comment]
Unforeseen challenges have delayed this feature.

**Comment by L-Guidos** [comment]
Opened issue #37 and issue #38 based on new discoveries while working on this

**Comment by kbef** [comment]
Done, @Ahmed-Har can close it once done testing.
