### ISSUE TITLE
Navigable Course Details

### ISSUE THREAD

**Issue by L-Guidos** [kbef/group1apk#27]
Goal: have the pre-reqs and post-reqs shown in Course Details screen to be clickable and take user to associated course details page for that course.

This will take rework as they are currently in text views and would need to be converted to individual buttons

**Comment by L-Guidos** [comment]
The course details are now navigable, but when the back button is pressed, it takes you back to course details. Is this okat @Ahmed-Har  and @kbef ?

**Comment by Ahmed-Har** [comment]
Yes it is.

**Comment by L-Guidos** [comment]
Fixed this issue and pushed changes to the UI branch
