### ISSUE TITLE
Pre Req Conflict Notification

### ISSUE THREAD

**Issue by L-Guidos** [kbef/group1apk#37]
We need a way to notify the user when they make a manual schedule change that causes a pre-req conflict. As discussed, if they choose yes, we will allow them to schedule it but we need to warn them they are creating a conflict.

**Comment by kbef** [comment]
Please test the custom Scheduling.

**Comment by L-Guidos** [comment]
It keeps a record of the pre and post reqs of a course even if you click cancel. We need to set this up so it wipes that data so when we try to add the next course, it does not exist.
